### ISSUE TITLE
Searching lost ancient source code from Tremulous SourceForge

### ISSUE THREAD

**Issue by LegendaryGuard** [darklegion/tremulous#25]
Hello, @timangus 

I'm searching the source code of `cg_mp3decoder.c` and `cg_mp3decoder.h`. 
I'm doing an experiment in a Quake 3 mod inside gamecode about this mp3 to wav converter.
I found that link: http://tremulous.sourceforge.net/junk/cg_mp3decoder/ from this old dev journal I was researching: 

https://github.com/LegendaryGuard/BFP/blob/main/docs/yrgol_dev_journal.md#mp3-support---11302001-by-yrgol
(original web reference: https://web.archive.org/web/20020205150340/http://www.bidforpower.com/journals/yrgol.php)

I was looking the SVN, and it was available in this revision (90): https://svn.icculus.org/tremulous?view=rev&revision=90
That only contains the cmd functions to execute the converter. But the files (`cg_mp3decoder.c` and `cg_mp3decoder.h`) aren't there.

And also I wanted to obtain the source code of `cg_spriter.c` and others from http://tremulous.sourceforge.net/junk/.

Do you have the old sources from http://tremulous.sourceforge.net/junk/ ?

I hope your answer.

**Comment by timangus** [comment]
If it's not in the repository I don't know where it is. Possibly I removed it (from the repository history itself) at some point due to licensing concerns. From what I can recall it was just an existing mp3 decode library altered to compile for the Q3 VM.

**Comment by LegendaryGuard** [comment]
Thanks for answering.
I wonder what library needs to be used in the source code for mp3 decoder. I wonder if someone got it, it should be in some site. Looks kinda hard to find.

The other way would be implementing from scratch, I don't know how it should be applied since it's Q3 gamecode and there are no external libraries.

**Comment by timangus** [comment]
Actually it seems the files are in the original 1.0 installers https://sourceforge.net/projects/tremulous/files/tremulous/1.0/

**Comment by LegendaryGuard** [comment]
> Actually it seems the files are in the original 1.0 installers https://sourceforge.net/projects/tremulous/files/tremulous/1.0/

Finally, I found it! Thank you. ;)
